import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pablo Martinez - Full Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
      {/* <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
         <div className="w-full flex-none md:w-64">
           <Sidebar />
         </div>
         <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
      </div> */}
      {children}
      </body>
    </html>
  );
}
